postgres_version: 15
postgres_data_dir: /var/lib/postgresql/data/pgdata
postgres_conf_src: postgresql.conf
postgres_conf_dest: /etc/postgresql/postgresql.conf
pgbackrest_conf_src: pgbackrest.conf
pgbackrest_conf_dest: /etc/pgbackrest/pgbackrest.conf
backup_cron_minute: '0'
backup_cron_hour: '2'